services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "4000:8000"
    volumes:
      - /home/node/app/node_modules
      - .:/home/node/app
  test:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /home/node/app/node_modules
      - .:/home/node/app
    command: ["npm", "run", "test"]
  
  